package app

const SQL_SCHEMA_POSTGRES = `

DROP TABLE IF EXISTS config CASCADE;
CREATE TABLE IF NOT EXISTS config (
	name TEXT UNIQUE NOT NULL,
	value TEXT NOT NULL
);

-- DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
	user_id SERIAL PRIMARY KEY NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	username VARCHAR(64) NULL UNIQUE
);
-- INSERT INTO USERS (username) values  ('hi');

DROP TABLE IF EXISTS projects CASCADE;
CREATE TABLE IF NOT EXISTS projects (
	project_id SERIAL PRIMARY KEY NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	name TEXT NOT NULL UNIQUE,
	user_id INTEGER,
	description TEXT NULL,
	state TEXT NOT NULL,
	deleted BOOLEAN NOT NULL DEFAULT false,
	archived BOOLEAN NOT NULL DEFAULT false,
	FOREIGN KEY (user_id) REFERENCES users(user_id)
);

DROP TABLE IF EXISTS tasks CASCADE;
CREATE TABLE IF NOT EXISTS tasks (
	task_id SERIAL PRIMARY KEY NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	due TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	user_id INTEGER,
	project_id INTEGER,
	state TEXT NOT NULL,
	name TEXT NOT NULL,
	description TEXT NULL,
	deleted BOOLEAN DEFAULT FALSE,
	archived BOOLEAN DEFAULT FALSE,
	FOREIGN KEY (user_id) REFERENCES users(user_id),
	FOREIGN KEY (project_id) REFERENCES projects(project_id)
);

DROP TABLE IF EXISTS project_comments CASCADE;
CREATE TABLE IF NOT EXISTS project_comments (
	comment_id SERIAL PRIMARY KEY NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	user_id INTEGER,
	project_id INTEGER,
	comment TEXT NOT NULL,
	description TEXT NULL,
	deleted BOOLEAN DEFAULT FALSE,
	archived BOOLEAN DEFAULT FALSE,
	FOREIGN KEY (user_id) REFERENCES users(user_id),
	FOREIGN KEY (project_id) REFERENCES projects(project_id)
);

DROP TABLE IF EXISTS task_comments CASCADE;
CREATE TABLE IF NOT EXISTS task_comments (
	comment_id SERIAL PRIMARY KEY NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	user_id INTEGER,
	task_id INTEGER,
	comment TEXT NOT NULL,
	description TEXT NULL,
	deleted BOOLEAN DEFAULT FALSE,
	archived BOOLEAN DEFAULT FALSE,
	FOREIGN KEY (user_id) REFERENCES users(user_id),
	FOREIGN KEY (task_id) REFERENCES tasks(task_id)
);
`
